// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from "flatbuffers";

import { Chunk } from "./chunk";

export class Bundle {
    bb: flatbuffers.ByteBuffer | null = null;
    bb_pos = 0;
    __init(i: number, bb: flatbuffers.ByteBuffer): Bundle {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }

    static getRootAsBundle(bb: flatbuffers.ByteBuffer, obj?: Bundle): Bundle {
        return (obj || new Bundle()).__init(
            bb.readInt32(bb.position()) + bb.position(),
            bb
        );
    }

    static getSizePrefixedRootAsBundle(
        bb: flatbuffers.ByteBuffer,
        obj?: Bundle
    ): Bundle {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new Bundle()).__init(
            bb.readInt32(bb.position()) + bb.position(),
            bb
        );
    }

    hash(index: number): number | null {
        const offset = this.bb!.__offset(this.bb_pos, 4);
        return offset
            ? this.bb!.readInt8(this.bb!.__vector(this.bb_pos + offset) + index)
            : 0;
    }

    hashLength(): number {
        const offset = this.bb!.__offset(this.bb_pos, 4);
        return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
    }

    hashArray(): Int8Array | null {
        const offset = this.bb!.__offset(this.bb_pos, 4);
        return offset
            ? new Int8Array(
                  this.bb!.bytes().buffer,
                  this.bb!.bytes().byteOffset +
                      this.bb!.__vector(this.bb_pos + offset),
                  this.bb!.__vector_len(this.bb_pos + offset)
              )
            : null;
    }

    chunks(index: number, obj?: Chunk): Chunk | null {
        const offset = this.bb!.__offset(this.bb_pos, 6);
        return offset
            ? (obj || new Chunk()).__init(
                  this.bb!.__indirect(
                      this.bb!.__vector(this.bb_pos + offset) + index * 4
                  ),
                  this.bb!
              )
            : null;
    }

    chunksLength(): number {
        const offset = this.bb!.__offset(this.bb_pos, 6);
        return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
    }

    static startBundle(builder: flatbuffers.Builder) {
        builder.startObject(2);
    }

    static addHash(
        builder: flatbuffers.Builder,
        hashOffset: flatbuffers.Offset
    ) {
        builder.addFieldOffset(0, hashOffset, 0);
    }

    static createHashVector(
        builder: flatbuffers.Builder,
        data: number[] | Int8Array
    ): flatbuffers.Offset;
    /**
     * @deprecated This Uint8Array overload will be removed in the future.
     */
    static createHashVector(
        builder: flatbuffers.Builder,
        data: number[] | Uint8Array
    ): flatbuffers.Offset;
    static createHashVector(
        builder: flatbuffers.Builder,
        data: number[] | Int8Array | Uint8Array
    ): flatbuffers.Offset {
        builder.startVector(1, data.length, 1);
        for (let i = data.length - 1; i >= 0; i--) {
            builder.addInt8(data[i]!);
        }
        return builder.endVector();
    }

    static startHashVector(builder: flatbuffers.Builder, numElems: number) {
        builder.startVector(1, numElems, 1);
    }

    static addChunks(
        builder: flatbuffers.Builder,
        chunksOffset: flatbuffers.Offset
    ) {
        builder.addFieldOffset(1, chunksOffset, 0);
    }

    static createChunksVector(
        builder: flatbuffers.Builder,
        data: flatbuffers.Offset[]
    ): flatbuffers.Offset {
        builder.startVector(4, data.length, 4);
        for (let i = data.length - 1; i >= 0; i--) {
            builder.addOffset(data[i]!);
        }
        return builder.endVector();
    }

    static startChunksVector(builder: flatbuffers.Builder, numElems: number) {
        builder.startVector(4, numElems, 4);
    }

    static endBundle(builder: flatbuffers.Builder): flatbuffers.Offset {
        const offset = builder.endObject();
        return offset;
    }

    static createBundle(
        builder: flatbuffers.Builder,
        hashOffset: flatbuffers.Offset,
        chunksOffset: flatbuffers.Offset
    ): flatbuffers.Offset {
        Bundle.startBundle(builder);
        Bundle.addHash(builder, hashOffset);
        Bundle.addChunks(builder, chunksOffset);
        return Bundle.endBundle(builder);
    }
}
